# Handles contact form submission (sending emails, etc)
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from cachetools import TTLCache
from datetime import datetime, timedelta
from os import environ
import smtplib

# Initialize the hourly email count cache
email_cache = TTLCache(maxsize=100, ttl= 60 * 60)  # Cache for 1 hour

def validate_email(name, subject, email, message):
    # Check hourly email count
    current_hour = datetime.now().replace(minute=0, second=0, microsecond=0)
    email_data = email_cache.get(current_hour, {'count': 0, 'last_modified': None})
    email_count = email_data['count']
    last_modified = email_data['last_modified']
    
    if email_count >= 10:
        # Remaining time in hours until the cache expires 
        remaining_time = (last_modified + timedelta(hours=1)) - datetime.now()
        return {'status': 'exceeded', 'remaining_time': remaining_time.seconds}

    # Send alert email
    sender_email = environ.get('EMAIL_USER')
    app_password = environ.get('EMAIL_PASS')
    recipient_email = environ.get('EMAIL_USER')
    email_subject = f"New Alert: {subject}"
    email_body = f"Name: {name}\nEmail: {email}\nMessage: {message}"
    
    if sender_email and app_password and recipient_email:
        # Send email to samir
        send_email(sender_email, app_password, recipient_email, email_subject, email_body)
        # Send email to user
        message = greeting(name, subject)
        send_email(sender_email, app_password, email, message["subject"], message["body"])    
        
        # Update email count and last modified time in cache
        email_cache[current_hour] = {'count': email_count + 1, 'last_modified': datetime.now()}
        response = {'status': 'success'}
        
    else: 
        print("Email credentials not found.")
        response = {'status': 'error'}
        
    return response

def send_email(sender_email, app_password, recipient_email, subject, body):
    """
    Sends an email to the recipient using Gmail's SMTP server
    
    Args:
        sender_email (str): Sender's email address
        app_password (str): App password generated by Gmail
        recipient_email (str): Recipient's email address
        subject (str): Subject of email
        body (str): Body of email
    """
    msg = MIMEMultipart()
    msg["From"] = sender_email
    msg["To"] = recipient_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    try: 
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, app_password)
        server.sendmail(sender_email, recipient_email, msg.as_string())
        server.quit()
    except Exception as e:
        print("An exception occurred while sending email.")
        print(e)
        
# Creates a greeting message 
def greeting(name, subject):
    """
    Creates a greeting message
    
    Args:
        name (str): Name of user
        subject (str): Subject of email
    Returns:
        dict: Dictionary containing subject and body of email
    """
    message = {}
    message["subject"] = f"Auto-reply: {subject}"
    message["body"] = f"Hello {name},\n\nThank you for contacting me about {subject}.\n\nI will get back to you as soon as possible.\n\nBest,\nSamir"
    return message